/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 whenever the process is running. Touches no dependency.
         */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Verifies every required dependency. Returns 503 with per-check detail when any is unhealthy, so the failing dependency is visible without log access.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DependencyCheck */
        DependencyCheck: {
            /**
             * Error
             * @description Failure summary; null when ok
             */
            error?: string | null;
            /**
             * Latency Ms
             * @description Wall-clock duration of the probe
             */
            latency_ms: number;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description Stable, machine-readable error code
             */
            code: string;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][];
            /**
             * Message
             * @description Human-readable summary; not for programmatic use
             */
            message: string;
            /**
             * Requestid
             * @description Correlation id, also returned in the X-Request-ID header
             */
            requestId?: string | null;
        };
        /**
         * ErrorDetail
         * @description A single field-level or item-level problem.
         */
        ErrorDetail: {
            /**
             * Location
             * @description Dotted path to the offending input
             */
            location?: string | null;
            /**
             * Message
             * @description Human-readable description of this specific problem
             */
            message: string;
            /**
             * Type
             * @description Machine-readable problem type
             */
            type?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** LivenessResponse */
        LivenessResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Checks */
            checks: components["schemas"]["DependencyCheck"][];
            /** Service */
            service: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaDependencyCheck = components['schemas']['DependencyCheck'];
export type SchemaErrorBody = components['schemas']['ErrorBody'];
export type SchemaErrorDetail = components['schemas']['ErrorDetail'];
export type SchemaErrorResponse = components['schemas']['ErrorResponse'];
export type SchemaLivenessResponse = components['schemas']['LivenessResponse'];
export type SchemaReadinessResponse = components['schemas']['ReadinessResponse'];
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
